### ISSUE TITLE
[enhancement] Adding getting started colab notebooks

### ISSUE THREAD

**Issue by mahimairaja** [Deci-AI/data-gradients#128]
The data-gradients package is much more friendly to make reports for image datasets. Making some notebooks could help the developers to get started. 

PS: Does the project is accepting any PR for the same?

**Comment by harpreetsahota204** [comment]
Hi @mahimairaja - this will be added on the official launch date of July 12. I've sent you a message on Linked with some early access materials.

**Comment by ofrimasad** [comment]
https://lnkd.in/gjB6KmmD
