### ISSUE TITLE
which version of pytorch and torchvision is required?

### ISSUE THREAD

**Issue by wonchul-kim** [Deci-AI/data-gradients#162]
### 💡 Your Question

I got this error:
cannot import name 'vit_b_16' from 'torchvision.models' 

for this:
from data_gradients.managers.segmentation_manager import SegmentationAnalysisManager

Is there required version of torch/torchvision ?

**Comment by ofrimasad** [comment]
Hi @wonchul-kim 
vit models were introduced in torchvision 0.12  (require torch > 1.11)
Hope that helps :)
